CREATE DATABASE consumer_behavior_project
USE consumer_behavior_project

SELECT *
FROM customer_behavior_analysis

--Business Insights Questions

--1. Which Category generates highest revenue

SELECT category, ROUND(SUM(purchase_amount),2) AS 'highest_revenue'
FROM customer_behavior_analysis
GROUP BY category
ORDER BY SUM(purchase_amount) DESC

--Comapany now knows which category has highest revenue
--Impact:
		-- It helps prioritize high-performing categories
		-- It helps in optimizing the inventory
		-- Improves marketing ROI, in which category to invest more.

--2. Have Discounts increased the purchase value ?

SELECT 
	discount_applied,
	ROUND(SUM(purchase_amount),2) as 'Revenue', 
	AVG(purchase_amount) as Average
FROM customer_behavior_analysis
GROUP BY discount_applied
ORDER BY Revenue DESC

-- Company now knows if giving disocunt increases the revenue or not
--Impact:
		-- Identify the effectiveness of discount
		-- Reduce giving unnecessary discount
		-- Improve profit margins

--3. What is the total revenue generated by male and female customer

SELECT gender, ROUND(SUM(purchase_amount),2) AS revenue
FROM customer_behavior_analysis
GROUP BY gender
ORDER BY revenue DESC

-- Company now knows the revenue contribution by gender segment
--Impact:
		-- It will help to design targeted marketing campaign
		-- Strategy according to gender segmentation to increase overall revenue
		-- Enhances personalization efforts

--4. Which customer used a discount but still spent more than the average purchase amount ?

SELECT TOP 10 customer_id, purchase_amount, discount_applied
FROM customer_behavior_analysis
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behavior_analysis)
ORDER BY purchase_amount DESC

--Q Customer dont use discount and still spend more than the average

SELECT TOP 10 customer_id, purchase_amount, discount_applied
FROM customer_behavior_analysis
WHERE discount_applied = 'No' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behavior_analysis)
ORDER BY purchase_amount DESC

-- Company can now identify its high spending customers who spends more than the average
--Impact:
		-- Identifies high spending customers
		-- Helps in improving customer retention

--5. What are the top and bottom 5 products with highest average review rating

SELECT TOP 5 item_purchased, SUM(purchase_amount) AS revenue, ROUND(AVG(review_rating),2) AS rating
FROM customer_behavior_analysis
GROUP BY item_purchased
ORDER BY rating DESC

SELECT TOP 5 item_purchased, SUM(purchase_amount) AS revenue, ROUND(AVG(review_rating),2) AS rating
FROM customer_behavior_analysis
GROUP BY item_purchased
ORDER BY rating ASC

-- Now the company knows the winning and Loosing Products
--Impact:
		-- Promotes high performance products
		-- Improves low rated products
		-- Takes measures on products to increase customer satisfaction

--6. Average purchase: Shipping-wise

SELECT shipping_type, COUNT(DISTINCT(customer_id)) AS customers, ROUND(SUM(purchase_amount),0) AS revenue, ROUND(AVG(purchase_amount),0) AS 'Avg_revenue'
FROM customer_behavior_analysis
GROUP BY shipping_type
ORDER BY revenue DESC

-- Now company knows which shipping service leads more revenue and customers
--Impact:
		-- Shipping pricing strategies
		-- Helps in increasing average order value

--7. Do subsdcribed customers spend more ?


SELECT subscription_status, ROUND(SUM(purchase_amount),2) AS revenue, COUNT(DISTINCT(customer_id)) AS customers
FROM customer_behavior_analysis
GROUP BY subscription_status
ORDER BY revenue DESC

--Now company knows about the effectiveness of subscription
--Impact:
		--Validates the subscription model
		-- Helps in taking measures to increase customer loyalty

--8. Top 5 products with highest discount usage

SELECT TOP 5
	item_purchased, 
	COUNT(item_purchased) AS no_of_sales,
	COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS sold_when_discount_applied,
	COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END)*100/COUNT(item_purchased) AS discount_percent
FROM customer_behavior_analysis
GROUP BY item_purchased
ORDER BY discount_percent DESC

--Now company knows which products are heavily dependent on discounts
--Impact:
		-- Identifies discount driven products
		-- Helps in price optimization
		-- Preventing profit margin loss

--9. Segment customer into new, returning and loyal based on their total number of previous purchase, and show the count of each segment.

SELECT 
    CASE
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Repeat Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment,
    
    COUNT(*) AS customer_count

FROM customer_behavior_analysis

GROUP BY 
    CASE
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Repeat Customer'
        ELSE 'Loyal Customer'
    END;

-- Now compamy knows the number of customers divided into segments
--Impact:
		-- It enables personalized marketing
		-- Improves retention strategies
		-- Increases conversion rates

--10. What are the top 3 most purchased products within each category ?

WITH ranked_products AS (
SELECT 
	category, 
	item_purchased, 
	COUNT(item_purchased) AS most_purchased,
	DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM customer_behavior_analysis
GROUP BY category, item_purchased)

SELECT *
FROM ranked_products
WHERE RNK <=3

--The company doesn’t know top-performing products within categories.
--Impact:
		--Improves product placement & recommendations
		--Helps inventory optimization
		--Increases sales through best-sellers

--11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END AS customer_type,
	subscription_status,
	COUNT(*) AS customer_count
FROM customer_behavior_analysis
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status

--Unclear relationship between loyalty and subscription.
--Impact:
			--Improves subscription targeting
			--Increases conversion to paid programs
			--increase customer retention strategy

--12. What is the revenue contribution of each age group ? 

SELECT
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group,
	ROUND(SUM(purchase_amount),2) AS revenue

FROM customer_behavior_analysis
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END
ORDER BY revenue DESC

--No visibility into which age group contributes most to revenue.
--Impact:-
			--Enables age-based targeting
			--Enhances marketing efficiency